---
development:
  cloud_name: dyo40bave
  api_key: '531312423968816'
  api_secret: _7vg7-vnJZHPQBzsKarcPRzORAI
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dyo40bave
  api_key: '531312423968816'
  api_secret: _7vg7-vnJZHPQBzsKarcPRzORAI
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dyo40bave
  api_key: '531312423968816'
  api_secret: _7vg7-vnJZHPQBzsKarcPRzORAI
  enhance_image_tag: true
  static_file_support: false
