default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "chris") %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: rails_cocktail_app_development

test:
  <<: *default
  database: rails_cocktail_app_test

production:
  <<: *default
  url: <%= GoogleSecrets.fetch("DATABASE_URL") %>
